import bank from "./question-bank.json";
import { getChapter } from "./catalog";
import type { Question } from "@/lib/types";

/**
 * Generated by `npm run bank:build` from `content/seed` and `content/imported`.
 * Never edit `question-bank.json` by hand.
 */
export const questionBank = bank as Question[];

const byId = new Map(questionBank.map((q) => [q.id, q]));

const byChapter = new Map<string, Question[]>();
for (const question of questionBank) {
  const list = byChapter.get(question.chapterId);
  if (list) list.push(question);
  else byChapter.set(question.chapterId, [question]);
}

if (process.env.NODE_ENV !== "production") {
  const orphans = [...byChapter.keys()].filter((id) => !getChapter(id));
  if (orphans.length > 0) {
    console.warn(
      `[question-bank] questions reference chapters missing from the catalog: ${orphans.join(", ")}`,
    );
  }
}

export function getQuestion(id: string): Question | undefined {
  return byId.get(id);
}

export function questionsForChapters(chapterIds: string[]): Question[] {
  return chapterIds.flatMap((id) => byChapter.get(id) ?? []);
}

/** Bank depth per chapter, shown on the chapter picker. */
export function questionCountsByChapter(): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const [chapterId, list] of byChapter) counts[chapterId] = list.length;
  return counts;
}
