with new_stems(stem) as (values
('If X is a discrete random variable with P(X = x) = k/2^x for x = 1, 2, 3, … then k equals'),
('For a binomial distribution with parameters n and p, the mean is'),
('Variance of a binomial random variable X ~ B(n, p) is'),
('If a continuous random variable has pdf f(x) = 2x on (0, 1), then P(X < 1/2) is'),
('E(aX + b) equals'),
('The order of the differential equation (d²y/dx²)³ + (dy/dx)⁴ + y = 0 is'),
('The degree of (dy/dx)² + 3(dy/dx) + 2y = 0 is'),
('The integrating factor of dy/dx + Py = Q (P, Q functions of x) is'),
('The solution of dy/dx = y/x (x ≠ 0) is'),
('A homogeneous differential equation of first order can be solved by substituting'),
('If f(x) = x² and g(x) = √x (x ≥ 0), then (f ∘ g)(x) equals'),
('A function f : A → B is one-one if'),
('The range of f(x) = sin x is'),
('If f is both one-one and onto, it is called'),
('To prove 1 + 2 + … + n = n(n+1)/2 by induction, the inductive step assumes the result for n = k and proves it for'),
('Mathematical induction is typically used to prove statements about'),
('If P(1) is true and P(k) ⇒ P(k+1) for all k ≥ 1, then'),
('The statement 2^n > n for all natural numbers n is best proved by'),
('If A is a square matrix of order 3, then |kA| equals'),
('If A is invertible, then (A⁻¹)⁻¹ equals'),
('A square matrix A is singular if and only if'),
('If A and B are compatible for multiplication, then (AB)ᵀ equals'),
('The system AX = B has a unique solution if A is'),
('The general solution of sin θ = 0 is'),
('The general solution of cos θ = 1/2 is'),
('Number of solutions of sin x = 1/2 in [0, 2π] is'),
('If tan θ = √3, a principal value of θ is'),
('The principal value of sin⁻¹(1/2) is'),
('sin⁻¹ x + cos⁻¹ x equals (for x ∈ [−1, 1])'),
('The domain of tan⁻¹ x is'),
('tan⁻¹(1) + tan⁻¹(1) equals'),
('cosh² x − sinh² x equals'),
('The derivative of sinh x with respect to x is'),
('In any triangle ABC, a/sin A equals'),
('Area of triangle ABC with sides a, b, c and included angle C is'),
('Heron’s formula gives area as √[s(s−a)(s−b)(s−c)] where s is'),
('In any triangle, r = Δ/s where r is the'),
('Cosine rule states that cos A equals'),
('The equation x² + y² = a² represents the locus of points at a fixed distance a from'),
('If a point moves so that its distance from a fixed point equals its distance from a fixed line, the locus is a'),
('The locus of the midpoint of a chord of slope m of the circle x² + y² = a² is'),
('Rotation of axes by angle θ (origin fixed) uses'),
('To remove the xy-term from a general conic by rotation, tan 2θ equals'),
('Shifting the origin does not change'),
('Slope of the line joining (x1, y1) and (x2, y2) is'),
('The equation of a line with slope m and y-intercept c is'),
('Two lines with slopes m1 and m2 are perpendicular if'),
('Distance from (x0, y0) to the line ax + by + c = 0 is'),
('The angle ψ between two lines with slopes m1, m2 satisfies tan ψ ='),
('The homogeneous equation ax² + 2hxy + by² = 0 represents a pair of lines through the origin if'),
('The angle between the pair ax² + 2hxy + by² = 0 satisfies tan θ ='),
('If the pair of lines ax² + 2hxy + by² = 0 are perpendicular, then'),
('Distance between A(x1,y1,z1) and B(x2,y2,z2) is'),
('The section formula dividing the join of A and B in ratio m : n internally has coordinates'),
('The midpoint of the segment joining (2, −1, 3) and (4, 5, −1) is'),
('If a, b, c are direction ratios, direction cosines are proportional to'),
('Direction cosines of the X-axis are'),
('Angle φ between two lines with DCs (l1,m1,n1) and (l2,m2,n2) satisfies cos φ ='),
('The Cartesian equation of a plane with normal vector ⟨a, b, c⟩ through (x0,y0,z0) is'),
('Distance from (x0,y0,z0) to the plane ax + by + cz + d = 0 is'),
('Two planes a1x + b1y + c1z + d1 = 0 and a2x + b2y + c2z + d2 = 0 are parallel if'),
('lim_{x→0} (sin x)/x equals'),
('lim_{x→0} (1 − cos x)/x² equals'),
('A function f is continuous at x = a if'),
('lim_{x→∞} (1 + 1/x)^x equals'),
('If lim_{x→a} f(x) = L and lim_{x→a} g(x) = M, then lim (f + g) equals'),
('De Moivre’s theorem states that [r(cos θ + i sin θ)]^n equals'),
('The n nth roots of unity lie on'),
('One value of √i is'),
('If z = cis θ, then z̄ equals'),
('For the cubic x³ + ax² + bx + c = 0, the sum of roots is'),
('For ax² + bx + c = 0 with a ≠ 0, product of roots is'),
('A polynomial equation of degree n has at most how many real roots?'),
('If α is a root of f(x) = 0, then (x − α) is a'),
('Descartes’ rule of signs gives an upper bound on the number of'),
('The partial fraction form of (x + 1)/[(x − 1)(x − 2)] is'),
('For a repeated linear factor (x − a)² in the denominator, partial fractions include'),
('Before decomposing into partial fractions, a proper rational function must satisfy'),
('An irreducible quadratic factor x² + 1 in the denominator contributes a term of the form'),
('Variance is the square of'),
('If each observation is increased by 5, the variance'),
('If each observation is multiplied by 2, the standard deviation is multiplied by'),
('The range of a data set is'),
('The equation S + λL = 0, where S = 0 is a circle and L = 0 a line, represents'),
('Two circles S1 = 0 and S2 = 0 are orthogonal if'),
('A coaxal system of circles has'),
('For the hyperbola x²/a² − y²/b² = 1, eccentricity e equals'),
('Asymptotes of x²/a² − y²/b² = 1 are'),
('The foci of x²/a² − y²/b² = 1 are at'),
('For a rectangular hyperbola, eccentricity equals'),
('xy = c² represents a'),
('∫_a^b f(x) dx + ∫_b^a f(x) dx equals'),
('∫_0^{π/2} sin x dx equals'),
('If f is continuous, ∫_a^a f(x) dx equals'),
('∫_0^a f(x) dx = ∫_0^a f(a − x) dx is true for'),
('The area under y = f(x) from x = a to x = b (f ≥ 0) is given by'),
('If a⃗ + b⃗ = 0, then'),
('The magnitude of a⃗ + b⃗ is maximum when a⃗ and b⃗ are'),
('Position vector of the midpoint of A and B with position vectors a⃗, b⃗ is'),
('Unit vector in the direction of a⃗ is'),
('a⃗ · b⃗ equals'),
('If a⃗ ⊥ b⃗, then a⃗ · b⃗ equals'),
('sin(A + B) equals'),
('sin C + sin D equals'),
('tan(A + B) equals'),
('The general term in the expansion of (a + b)^n is'),
('The middle term(s) in (a + b)^8 occur at'),
('C(n, r) + C(n, r − 1) equals'),
('The constant term in (x + 1/x)^6 is the coefficient of'),
('For the ellipse x²/a² + y²/b² = 1 (a > b), eccentricity e equals'),
('Sum of focal distances of any point on an ellipse is'),
('The foci of x²/a² + y²/b² = 1 (a > b) are at'),
('Length of the latus rectum of the ellipse x²/a² + y²/b² = 1 is'),
('∫ x^n dx (n ≠ −1) equals'),
('∫ (1/x) dx equals'),
('∫ e^x dx equals'),
('∫ sin x dx equals'),
('At a local maximum of a differentiable function, f′(x) is'),
('The slope of the tangent to y = f(x) at x = a is'),
('If f′(x) > 0 on an interval, then f is'),
('Rolle’s theorem requires f(a) = f(b) and concludes there exists c in (a, b) with'),
('The number of permutations of n distinct objects taken r at a time is'),
('C(n, r) equals'),
('C(n, r) = C(n, n − r) is true for'),
('Number of ways to choose 3 students from 10 is'),
('If z = x + iy, then |z| equals'),
('i² equals'),
('The conjugate of x + iy is'),
('z z̄ equals'),
('cosh x is defined as'),
('sech x equals'),
('The locus of a point which moves at a fixed distance from a fixed point is a'),
('After translating the origin to (2, -3), the point (5, 1) has new coordinates'),
('The homogeneous quadratic ax^2 + 2hxy + by^2 = 0 always represents lines passing through'),
('The equation of the YZ-plane is'),
('If the direction cosines of a line are proportional to 2, 3, 6, then the actual DCs are'),
('The plane x/2 + y/3 + z/4 = 1 has X-intercept equal to'),
('The common chord of two intersecting circles is the same as their'),
('If |a| = 3, |b| = 4 and the angle between them is 90 degrees, then |a x b| equals'),
('a · (a x b) equals'),
('cos(A + B) equals')
)
select count(*)::int as checked,
       count(*) filter (where exists (
         select 1 from question_bank qb
         where qb.subject_id = 'maths'
           and lower(regexp_replace(qb.stem, '[^a-zA-Z0-9]+', ' ', 'g'))
             = lower(regexp_replace(new_stems.stem, '[^a-zA-Z0-9]+', ' ', 'g'))
       ))::int as already_in_db
from new_stems;