import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { repoRoot, bankFile } from "./lib/bank.mjs";
import {
  chapters,
  exams,
  streams,
  subjects,
} from "../src/content/catalog.ts";

const outFile = path.join(repoRoot, "supabase", "seed.sql");

function quote(value) {
  if (value === null || value === undefined) return "null";
  return `'${String(value).replace(/'/g, "''")}'`;
}

function json(value) {
  return `${quote(JSON.stringify(value))}::jsonb`;
}

function intArray(values) {
  return `'{${values.join(",")}}'::int[]`;
}

function textArray(values) {
  return `'{${values.map((v) => `"${String(v).replace(/"/g, '\\"')}"`).join(",")}}'::text[]`;
}

const questions = JSON.parse(await readFile(bankFile, "utf8"));

const lines = [
  "-- Generated by `npm run seed:sql`. Do not edit by hand.",
  "begin;",
  "",
  "-- catalog",
];

for (const subject of subjects) {
  lines.push(
    `insert into subjects (id, name) values (${quote(subject.id)}, ${quote(subject.name)})` +
      " on conflict (id) do update set name = excluded.name;",
  );
}

for (const stream of streams) {
  lines.push(
    `insert into streams (id, name) values (${quote(stream.id)}, ${quote(stream.name)})` +
      " on conflict (id) do update set name = excluded.name;",
  );
  for (const subjectId of stream.subjectIds) {
    lines.push(
      `insert into stream_subjects (stream_id, subject_id) values (${quote(stream.id)}, ${quote(subjectId)})` +
        " on conflict do nothing;",
    );
  }
}

for (const exam of exams) {
  lines.push(
    "insert into exams (id, name, authority, duration_minutes, marking) values (" +
      [
        quote(exam.id),
        quote(exam.name),
        quote(exam.authority),
        exam.durationMinutes,
        json(exam.marking),
      ].join(", ") +
      ") on conflict (id) do update set name = excluded.name, authority = excluded.authority," +
      " duration_minutes = excluded.duration_minutes, marking = excluded.marking;",
  );

  for (const [streamId, quotas] of Object.entries(exam.quotas)) {
    for (const quota of quotas ?? []) {
      lines.push(
        "insert into exam_quotas (exam_id, stream_id, subject_id, question_count) values (" +
          [quote(exam.id), quote(streamId), quote(quota.subjectId), quota.count].join(", ") +
          ") on conflict (exam_id, stream_id, subject_id) do update set question_count = excluded.question_count;",
      );
    }
  }
}

for (const chapter of chapters) {
  lines.push(
    "insert into chapters (id, subject_id, name, year) values (" +
      [quote(chapter.id), quote(chapter.subjectId), quote(chapter.name), chapter.year].join(", ") +
      ") on conflict (id) do update set name = excluded.name, year = excluded.year;",
  );
}

lines.push("", "-- question bank");

for (const question of questions) {
  lines.push(
    "insert into question_bank (id, chapter_id, subject_id, stem, options, answer_index, explanation, source) values (" +
      [
        quote(question.id),
        quote(question.chapterId),
        quote(question.subjectId),
        quote(question.stem),
        json(question.options),
        question.answerIndex,
        quote(question.explanation ?? ""),
        json(question.source),
      ].join(", ") +
      ") on conflict (id) do update set stem = excluded.stem, options = excluded.options," +
      " answer_index = excluded.answer_index, explanation = excluded.explanation, source = excluded.source;",
  );
  lines.push(
    "insert into question_pyq_meta (question_id, appear_count, years, exams, verified) values (" +
      [
        quote(question.id),
        question.pyq.appearCount,
        intArray(question.pyq.years),
        textArray(question.pyq.exams),
        question.pyq.verified ? "true" : "false",
      ].join(", ") +
      ") on conflict (question_id) do update set appear_count = excluded.appear_count," +
      " years = excluded.years, exams = excluded.exams, verified = excluded.verified;",
  );
}

lines.push("", "commit;", "");

await mkdir(path.dirname(outFile), { recursive: true });
await writeFile(outFile, lines.join("\n"), "utf8");

console.log(
  `Wrote ${outFile}\n  subjects: ${subjects.length}\n  chapters: ${chapters.length}\n  exams: ${exams.length}\n  questions: ${questions.length}`,
);
